name: java-service-ci
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

permissions:
  checks: write

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v3
        id: setup-gradle
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-results
          path: 'build/reports/jacoco/test/jacocoTestReport.csv'
          retention-days: 1

  jacoco-report:
    runs-on: ubuntu-latest
    needs: [ java-build ]
    steps:
      - name: Download Jacoco Report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-results

      - name: show all files
        run: ls -R

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          intervals: '85 80 75 70 60 50'
          generate-branches-badge: true
          jacoco-csv-file: 'jacocoTestReport.csv'

  auto-approve:
    runs-on: ubuntu-latest
    needs: [ java-build ]
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - run: echo "{{github.actor}} is a bot, auto-approving".
      - uses: hmarr/auto-approve-action@v4
