name: owner-auto-approve
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - 'test/**'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'emax19'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}